### ISSUE TITLE
The vips_call function seems to stop after 16 invocations

### ISSUE THREAD

**Issue by mhirsch** [libvips/nip2#92]
I'm attaching a nip2 worksheet that shows an example of this. (I had to rename the extension to `.txt` to attach it to this issue).

[vips_callImageSaveTest.ws.txt](https://github.com/libvips/nip2/files/5443002/vips_callImageSaveTest.ws.txt)

The sheet creates a list of images, and defines a function to accept the list of images and list of filenames and save them to files using `vips_call` with `vipssave`. I've found this pattern useful for saving unknown numbers of images in batch mode.

However, when the length of the list exceeds 16, it seems only the first 16 images are saved. A workaround would be to split up the list and operate on sub-lists of length 16 or less, but if there's something I'm missing here I'd appreciate a pointer! Thank you!

**Comment by jcupitt** [comment]
Hi @mhirsch,

Huh I hadn't thought of calling savers like that. I think you're having problems because of lazy evaluation: there's nothing forcing the whole list to execute.

Try starting nip2 and entering `primes`. This is a function that generates an infinite list of prime numbers using the sieve of Eratosthenes. The list is generated lazily, with evaluation driven by the need to create output. In this case, the demand is the thing that draws the value display next to A1. In your example, I think it's computing enough of the list to be able to make a value string (even though there's no GUI) and stopping.

You need to force it to compute the whole list. A successful save should return `[]`, so you need to walk down the list verifying that you have `[]` in every element. Something like (untested):

```
check_save_OK = if foldr1 logical_and (map (equal []) A1) then "OK!" else error "save failed!"
```

The official way to save a list of images is to use `Group`, I guess you know about this?

**Comment by mhirsch** [comment]
Thank you for this answer! That's very clear.

I've been using this method of saving files rather than groups when I have the situation where a sheet should take multiple inputs and generate multiple sets of outputs. E.g. I want to process a group of 20 images, create 20 thumbnails and 20 deep zoom pyramids. Is there a better way to have a sheet write multiple sets of outputs without re-running it? Since there is some processing involved leading up to the thumbnail and pyramid writing, re-running the entire sheet with those two separate outputs is significantly longer than running it once and writing both.

**Comment by jcupitt** [comment]
You can use `Group` for that, eg.

```
main = Group [A1, A2, A3];
```

Now run the workspace as `nip2 -b x.ws -o fred001.dz` and it's write the three images in the group to `fred001.dz`, `fred002.dz` and `fred003.dz`. You don't get much control over the filenames, of course.

**Comment by mhirsch** [comment]
That's the solution I've been using when I want one type of output from a worksheet. I'm wondering if there's a way to get multiple groups to write output files without running the sheet twice specifying different `main`s?

**Comment by jcupitt** [comment]
Ah, gotcha. 

No, something like `check_save_OK` might be best.

**Comment by mhirsch** [comment]
It seems to work well! Thanks again.
